http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer-when-downgrade"
        customFrameOptionsValue: "SAMEORIGIN"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"
