name: Deploy (Self-Hosted Runner)

on:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, vps, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull images & build
        run: |
          docker compose pull || true
          docker compose build
          docker compose up -d

      - name: Healthcheck
        run: |
          set -e
          for i in $(seq 1 30); do
            curl -fsS "http://localhost:3001/health" && exit 0
            sleep 2
          done
          echo "Healthcheck failed"; exit 1
